name: Fullstack CI

on:
  push:
    branches: [ main ]
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    -uses: actions/checkout@v2
    -name: setup
     run:
     cd backend
      npm install
    -name: Frontend setup
     run:
     cd frontend
      npm install
      npm run build



    
      